# Generated by Django 5.0.1 on 2024-02-08 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro_7', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherr',
            name='gender',
            field=models.TextField(default='male'),
            preserve_default=False,
        ),
    ]
