# Generated by Django 5.0.1 on 2024-02-08 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pro_7', '0002_teacherr_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherr',
            name='gender',
        ),
    ]
