# Generated by Django 5.0.1 on 2024-02-08 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pro_7', '0003_remove_teacherr_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacherr',
            old_name='department',
            new_name='gender',
        ),
    ]
